create extension if not exists pgcrypto;

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    email text,
    role text not null default 'manager' check (role in ('admin', 'manager')),
    full_name text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create or replace function public.set_updated_at()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

drop trigger if exists profiles_set_updated_at on public.profiles;

create trigger profiles_set_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

create or replace function public.create_profile_for_new_user()
returns trigger as $$
begin
    insert into public.profiles (id, email, role, full_name)
    values (
        new.id,
        new.email,
        case
            when new.raw_user_meta_data->>'role' in ('admin', 'manager')
                then new.raw_user_meta_data->>'role'
            else 'manager'
        end,
        new.raw_user_meta_data->>'full_name'
    )
    on conflict (id) do update
    set
        email = excluded.email,
        role = excluded.role,
        full_name = excluded.full_name;

    return new;
end;
$$ language plpgsql security definer set search_path = public;

drop trigger if exists auth_users_create_profile on auth.users;

create trigger auth_users_create_profile
after insert on auth.users
for each row
execute function public.create_profile_for_new_user();

alter table public.profiles enable row level security;

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
on public.profiles
for select
using (auth.uid() = id);

create table if not exists public.post_types (
    id integer generated by default as identity primary key,
    name text not null,
    slug text not null unique
);

insert into public.post_types (id, name, slug)
values
    (1, 'Announcement', 'announcement'),
    (2, 'News', 'news'),
    (3, 'Hiring', 'hiring'),
    (4, 'Event', 'event')
on conflict (id) do update
set
    name = excluded.name,
    slug = excluded.slug;

select setval(
    pg_get_serial_sequence('public.post_types', 'id'),
    greatest((select max(id) from public.post_types), 1)
);

alter table public.post_types enable row level security;

drop policy if exists "Anyone can read post types" on public.post_types;
create policy "Anyone can read post types"
on public.post_types
for select
using (true);

create table if not exists public.posts (
    id uuid primary key default gen_random_uuid(),
    title text not null,
    slug text not null unique,
    content text not null,
    type_id integer not null references public.post_types(id),
    cover_image text,
    published boolean not null default false,
    featured boolean not null default false,
    created_by uuid references auth.users(id) on delete set null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

drop trigger if exists posts_set_updated_at on public.posts;

create trigger posts_set_updated_at
before update on public.posts
for each row
execute function public.set_updated_at();

create table if not exists public.post_images (
    id uuid primary key default gen_random_uuid(),
    post_id uuid not null references public.posts(id) on delete cascade,
    image_path text not null,
    caption text,
    sort_order integer not null default 0,
    created_at timestamp with time zone not null default now()
);

do $$
begin
    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'post_images'
          and column_name = 'image_url'
    ) and not exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'post_images'
          and column_name = 'image_path'
    ) then
        alter table public.post_images rename column image_url to image_path;
    end if;
end;
$$;

create index if not exists profiles_role_idx on public.profiles(role);
create index if not exists posts_type_id_idx on public.posts(type_id);
create index if not exists posts_published_created_at_idx
    on public.posts(published, created_at desc);
create index if not exists posts_featured_idx on public.posts(featured);
create index if not exists post_images_post_id_sort_order_idx
    on public.post_images(post_id, sort_order);

alter table public.posts enable row level security;
alter table public.post_images enable row level security;

drop policy if exists "Anyone can read published posts" on public.posts;
create policy "Anyone can read published posts"
on public.posts
for select
using (published = true);

drop policy if exists "Anyone can read images for published posts" on public.post_images;
create policy "Anyone can read images for published posts"
on public.post_images
for select
using (
    exists (
        select 1
        from public.posts
        where posts.id = post_images.post_id
          and posts.published = true
    )
);

insert into storage.buckets (id, name, public)
values ('website', 'website', true)
on conflict (id) do update
set
    name = excluded.name,
    public = excluded.public;

drop policy if exists "Anyone can read website files" on storage.objects;
create policy "Anyone can read website files"
on storage.objects
for select
using (bucket_id = 'website');
